# Stage 1: Build
FROM golang:1.25.5-alpine3.21 AS builder

ENV GO111MODULE=on \
    CGO_ENABLED=0 \
    GOOS=linux \
    GOARCH=amd64

WORKDIR /build

COPY go.mod go.sum ./
RUN go mod download

COPY . .
# 编译 Redirect Server
RUN go build -o redirect-server ./cmd/redirect-server

# Stage 2: Runtime
FROM alpine:3.21

RUN apk --no-cache add ca-certificates tzdata

WORKDIR /app

COPY --from=builder /build/redirect-server .

EXPOSE 8080

CMD ["./redirect-server"]